# Discord bot token
token: "DISCORD_BOT_TOKEN"

# Discord bot status
statusMode: ONLINE # Valid Modes: ONLINE, IDLE, DND, INVISIBLE"
statusType: WATCHING # Valid Types: PLAYING, LISTENING, WATCHING, COMPETING, NONE
statusText: "My Velocity Bot"

database:
  type: SQLITE # Valid types: SQLITE, MYSQL
  sqlite-file: "database.db"
  mysql:
    host: localhost
    port: 3306
    database: discordbridge
    username: user
    password: pass

link:
  guild-id: "123456789123456789" # Replace with your guild ID (Server ID)
  change_discord_name: false # Change Discord nickname to in-game username upon linking
  give_role: # Give a role upon linking
    enabled: false
    role_id: "123456789123456789" # Replace with your role ID

discord_messages:
  link-message:
    title: "🔗 Link Your Account"
    color: 214000203 # RGB without commas
    message:
      - "**Link your Discord account with your in-game account!**"
      - ""
      - "1. Join the Minecraft Server: www.example.com"
      - "2. Run the command: `/link {code}` in-game"
      - ""
      - "**This link code will expire in 5 minutes.**"
  dm: "✅ Message sent via DM."
  dm-error:
    title: "⚠️ Unable to send DM"
    color: 250000000
    message: "Please, enable your DMs to receive messages from the bot."
  already-linked:
    title: "⚠️ Account Already Linked"
    color: 250000000
    message: "Your Discord account is already linked with an in-game account: {username}"
  link-successfully:
    title: "You have successfully linked your account!"
    color: 008199002
    message:
      - "**You have successfully linked your account!**"
      - ""
      - "Your in-game username: `{username}`"
      - "Recovery Code: `{recovery_code}`"
      - ""
      - "**Save this code to make changes to the link**"
      - "**Do not share it with ANYONE**"
  info-not-linked:
    title: "⚠️ Account Not Linked"
    color: 250000000
    message:
      - "Your Discord account is not linked with any in-game account."
      - "To link your account, use `/link`"
  info:
    title: "🔗 Linked Account Information"
    color: 214000203
    message:
      - "**Your Discord account is linked with the following in-game account:**"
      - ""
      - "Username: `{username}`"
      - ""
      - "To unlink your account, use `/unlink`"

messages:
  invalid-expired: "&cInvalid or expired link code"
  link-success: "✅ In-Game account successfully linked with Discord!"
  link-error: "&cError linking accounts."
  link-command: "&cUsage: /link <code>. You can get the code in Discord by using /link on any channel."
  already-linked: "&c⚠️ Your account is already linked with a Discord account."